<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="21269" started-at="2020-03-08T11:21:46 IST" finished-at="2020-03-08T11:22:07 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="21269" started-at="2020-03-08T11:21:46 IST" finished-at="2020-03-08T11:22:07 IST">
      <class name="com.movemoney.zelle.users.TestUsers">
        <test-method status="PASS" signature="beforemethod()[pri:0, instance:com.movemoney.zelle.users.TestUsers@1f554b06]" name="beforemethod" is-config="true" duration-ms="10124" started-at="2020-03-08T11:21:46 IST" finished-at="2020-03-08T11:21:56 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforemethod -->
        <test-method status="FAIL" signature="SB()[pri:1, instance:com.movemoney.zelle.users.TestUsers@1f554b06]" name="SB" duration-ms="16" started-at="2020-03-08T11:21:56 IST" finished-at="2020-03-08T11:21:56 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [User Created Sucessfully.] but found [User created.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [User Created Sucessfully.] but found [User created.]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.movemoney.zelle.users.TestUsers.SB(TestUsers.java:38)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SB -->
        <test-method status="PASS" signature="aftermethod()[pri:0, instance:com.movemoney.zelle.users.TestUsers@1f554b06]" name="aftermethod" is-config="true" duration-ms="1646" started-at="2020-03-08T11:21:56 IST" finished-at="2020-03-08T11:21:58 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftermethod -->
        <test-method status="PASS" signature="beforemethod()[pri:0, instance:com.movemoney.zelle.users.TestUsers@1f554b06]" name="beforemethod" is-config="true" duration-ms="7522" started-at="2020-03-08T11:21:58 IST" finished-at="2020-03-08T11:22:05 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforemethod -->
        <test-method status="PASS" signature="Hyrbid()[pri:2, instance:com.movemoney.zelle.users.TestUsers@1f554b06]" name="Hyrbid" duration-ms="2" started-at="2020-03-08T11:22:05 IST" finished-at="2020-03-08T11:22:05 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Hyrbid -->
        <test-method status="PASS" signature="aftermethod()[pri:0, instance:com.movemoney.zelle.users.TestUsers@1f554b06]" name="aftermethod" is-config="true" duration-ms="1883" started-at="2020-03-08T11:22:05 IST" finished-at="2020-03-08T11:22:07 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftermethod -->
        <test-method status="SKIP" signature="Consumer()[pri:3, instance:com.movemoney.zelle.users.TestUsers@1f554b06]" name="Consumer" duration-ms="0" started-at="2020-03-08T11:22:07 IST" depends-on-methods="com.movemoney.zelle.users.TestUsers.SB" finished-at="2020-03-08T11:22:07 IST">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestUsers.Consumer()[pri:3, instance:com.movemoney.zelle.users.TestUsers@1f554b06] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestUsers.Consumer()[pri:3, instance:com.movemoney.zelle.users.TestUsers@1f554b06] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:101)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Consumer -->
      </class> <!-- com.movemoney.zelle.users.TestUsers -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
